// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGUio7d5cM5LzlBKTRJ3SX0VAZJsAQAvw',
    appId: '1:563307851415:web:608750f3bccb028eef43d2',
    messagingSenderId: '563307851415',
    projectId: 'bellycoinfire',
    authDomain: 'bellycoinfire.firebaseapp.com',
    storageBucket: 'bellycoinfire.appspot.com',
    measurementId: 'G-NECNEZLQ60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWegaFZVrB7Hww7dll7m_X4Whw3DQ9V6U',
    appId: '1:563307851415:android:f76728887ab189acef43d2',
    messagingSenderId: '563307851415',
    projectId: 'bellycoinfire',
    storageBucket: 'bellycoinfire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7kmmRYCvscRzxHCxhMY4-3tUP2KFRh0o',
    appId: '1:563307851415:ios:0df344187c25e0b8ef43d2',
    messagingSenderId: '563307851415',
    projectId: 'bellycoinfire',
    storageBucket: 'bellycoinfire.appspot.com',
    androidClientId: '563307851415-ji7rk7u905im22en466kr6asqbeldqf9.apps.googleusercontent.com',
    iosClientId: '563307851415-unbn2ug1lfke0idf8lhhfkg9vtlmd491.apps.googleusercontent.com',
    iosBundleId: 'com.example.bellycoinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7kmmRYCvscRzxHCxhMY4-3tUP2KFRh0o',
    appId: '1:563307851415:ios:0df344187c25e0b8ef43d2',
    messagingSenderId: '563307851415',
    projectId: 'bellycoinfire',
    storageBucket: 'bellycoinfire.appspot.com',
    androidClientId: '563307851415-ji7rk7u905im22en466kr6asqbeldqf9.apps.googleusercontent.com',
    iosClientId: '563307851415-unbn2ug1lfke0idf8lhhfkg9vtlmd491.apps.googleusercontent.com',
    iosBundleId: 'com.example.bellycoinApp',
  );
}
